
markdown: kramdown
baseurl: /demoproj
exclude: ['README.md']
future: true
permalink: pretty   # /:categories/:title.html


kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3


sudo:          false
language:      node_js
node_js:
  - "node"
install:       npm install
script:
  - npm test
  - gulp
cache:
  directories:
    - node_modules
